xpathtool: XPathTool Class Reference
XPathTool Class Reference
XPathTool is a relatively uncomplicated wrapper for an XPath action: it doesn't know what you're doing, and doesn't assume you'll do things in a specific order, but tries to stop you from making really silly errors like saving or searching an unloaded file.
Public Member Functions
XPathTool (String xmlFile)
Class Constructor to create with an initial file to load.
XPathTool ()
Class Constructor with no initial file.
void load (String xmlFile)
Wrapper to just load the file, spitting out exceptions and stacks as they occur.
void save (String out)
Wrapper to just save the file, spitting out exceptions and stacks as they occur.
Object search (String expression, QName returnType) throws org.smallfoot.xpath.NoDocumentException
Search the current XML Document for a match, returning a list of matching nodes.
Static Public Member Functions
static int setAttr (NodeList nodelist, String replacement)
Consume a list of matches, and for each node (entity or attribute) replace the current value.
static int subAttr (NodeList nodelist, String editMatch, String editReplace, boolean global)
Consume a list of matches, and for each node (entity or attribute) make a Strong.replaceFirst() or a String.replaceAll()
Protected Member Functions
void _load (String xmlFile) throws javax.xml.parsers.ParserConfigurationException, org.xml.sax.SAXException, java.io.IOException
Open a file.
void _save (String xmlFile) throws javax.xml.transform.TransformerConfigurationException, java.io.FileNotFoundException, javax.xml.transform.TransformerException, org.smallfoot.xpath.NoDocumentException
Save the current XML Document to a new file.
Private Attributes
org.w3c.dom.Document xmlDocument
Detailed Description
XPathTool is a relatively uncomplicated wrapper for an XPath action: it doesn't know what you're doing, and doesn't assume you'll do things in a specific order, but tries to stop you from making really silly errors like saving or searching an unloaded file.
Definition at line 17 of file XPathTool.java.
Constructor & Destructor Documentation
XPathTool (String xmlFile) inline
Class Constructor to create with an initial file to load.
Parameters
xmlFile File to load at start
See Also
load(String)
Definition at line 28 of file XPathTool.java.
References XPathTool.load().
Member Function Documentation
void _load (String xmlFile) throws javax.xml.parsers.ParserConfigurationException, org.xml.sax.SAXException, java.io.IOException inline protected
Open a file.
This is actually a wrapper for the complex usage of javax.xml.parsers.DocumentBuilderFactory to find a singleton to instantiate a document from a file.
Parameters
xmlFile file to load
Exceptions
java.io.IOException on issues loading the file given as a parameter
javax.xml.parsers.ParserConfigurationException when the javax.xml.parsers.DocumentBuilderFactory is butchered
org.xml.sax.SAXException on parsing issues
Definition at line 50 of file XPathTool.java.
Referenced by XPathTool.load().
void _save (String xmlFile) throws javax.xml.transform.TransformerConfigurationException, java.io.FileNotFoundException, javax.xml.transform.TransformerException, org.smallfoot.xpath.NoDocumentException inline protected
Save the current XML Document to a new file.
based partially on DocumentBuilderFactory.java and influenced by Writing XML on Android
Parameters
xmlFile filename to save into
Exceptions
java.io.FileNotFoundException on issues creating the output filestream on xmlFile (ie missing interposing directory or permissions)
javax.xml.transform.TransformerConfigurationException when the javax.xml.transform.TransformerFactory is butchered
javax.xml.transform.TransformerException for exceptions on the final step, the transformation itself
org.smallfoot.xpath.NoDocumentException if the user has tried to search before a document is loaded
Definition at line 87 of file XPathTool.java.
Referenced by XPathTool.save().
void load (String xmlFile) inline
Wrapper to just load the file, spitting out exceptions and stacks as they occur.
Parameters
xmlFile file to load
Definition at line 61 of file XPathTool.java.
References XPathTool._load().
Referenced by XPathTool.XPathTool().
void save (String out) inline
Wrapper to just save the file, spitting out exceptions and stacks as they occur.
Parameters
out filename to save into
Definition at line 106 of file XPathTool.java.
References XPathTool._save().
Object search (String expression, QName returnType) throws org.smallfoot.xpath.NoDocumentException inline
Search the current XML Document for a match, returning a list of matching nodes.
Parameters
expression XPath expression to search for
returnType namespace context against which the expression is evaluated
Exceptions
org.smallfoot.xpath.NoDocumentException if the user has tried to search before a document is loaded
Definition at line 129 of file XPathTool.java.
Referenced by XPathSub.main(), and XPathSet.main().
static int setAttr (NodeList nodelist, String replacement) inline static
Consume a list of matches, and for each node (entity or attribute) replace the current value.
This function allows specific programmatic replacement of string values in XML to reduce the chance of user error and typos creating erroneous XML.
Parameters
nodelist list of nodes containing targets/matches to alter
replacement string to replace for matches
Returns
number of matches made
Definition at line 202 of file XPathTool.java.
static int subAttr (NodeList nodelist, String editMatch, String editReplace, boolean global) inline static
Consume a list of matches, and for each node (entity or attribute) make a Strong.replaceFirst() or a String.replaceAll()
This function is added as a convenience function to allow semi-contextual replacement of strings when converting other XML content – this allows single atomic commands to rename components to avoid name-clashes and unintended replacements.
Parameters
nodelist list of nodes containing targets/matches to alter
editMatch string to match for replacement
editReplace string to replace for matches
global whether to replace globally (like sed -e 's/X/y/g' – the 'g' at the end) – which is whether to use a Strong.replaceFirst() or a String.replaceAll()
Returns
number of matches made
Definition at line 158 of file XPathTool.java.
The documentation for this class was generated from the following file:
java/XPathTool.java