xpathtool: XPathSub Class Reference
XPathSub Class Reference
A driving class to interpret commandline arguments and pass them to the underlying XPathTool.
Public Member Functions
XPathSub ()
Class Constructor, uncomplicated.
Static Public Member Functions
static void main (String[] args)
main(args) handles the processing of arguments as sequential actions to pass to the underlying XPathTool.
Private Attributes
int replacements = 0
counts the number of replacements completed
Detailed Description
A driving class to interpret commandline arguments and pass them to the underlying XPathTool.
Definition at line 11 of file XPathSub.java.
Member Function Documentation
static void main (String[] args) inline static
main(args) handles the processing of arguments as sequential actions to pass to the underlying XPathTool.
Parameters
args commandline arguments for processing:
-i loads a file (see XPathTool#load(String))
-o saves a file (see XPathTool#save(String))
-r sets a replacement expression: anything "found" while running a "-f" argument is munged by this value
-f starts a search, replacing the value of all matching nodes and attributes with the replcement value given
Definition at line 31 of file XPathSub.java.
References XPathTool.load(), XPathTool.save(), XPathTool.search(), and XPathTool.subAttr().
The documentation for this class was generated from the following file:
java/XPathSub.java