xpathtool: XPathSet Class Reference
XPathSet Class Reference
A driving class to interpret commandline arguments and pass them to the underlying XPathTool.
Public Member Functions
XPathSet ()
Class Constructor, uncomplicated.
Static Public Member Functions
static void main (String[] args)
main(args) handles the processing of arguments as sequential actions to pass to the underlying XPathTool.
static void usage (String proc)
usage messages are useful to those of us with short memories as well (hey, I just need to add swap!)
Private Attributes
int replacements = 0
counts the number of replacements completed
Detailed Description
A driving class to interpret commandline arguments and pass them to the underlying XPathTool.
Definition at line 11 of file XPathSet.java.
Member Function Documentation
static void main (String[] args) inline static
main(args) handles the processing of arguments as sequential actions to pass to the underlying XPathTool.
Parameters
args commandline arguments for processing:
-i loads a file (see XPathTool#load(String))
-o saves a file (see XPathTool#save(String))
-r sets a replacement value: anything "found" while running a "-f" argument is replaced by this value
-f starts a search, replacing the value of all matching nodes and attributes with the replacement (-r) value given
-R sets a replacement pattern: ie /from/to/g : anything "found" while running a "-f" argument, all "from" are replaced by "to". "g" as the last parameter allows multiple replacements per matching node
-F starts a search, triggering -R replacement on values on all matching nodes
-V shows version and quits
Commandline Options:
-F execute a search using the replacement already registered: for each matching node, execute the replacement
Commandline Options:
java -jar xpathtool.jar -i .. -r .. -F "//ScanTask[@name='VWVersionSearch']/@file" -o ..
Commandline Options:
The format of the search string is a standard XPath expression
See also
http://en.wikipedia.org/wiki/XPath
http://www.w3.org/TR/xpath/
Commandline Options:
-o save an XML file after editing
Commandline Options:
-i read in an XML file for editing
Always always ALWAYS provide a quick reference and a version output
Commandline Options:
-H Show a simple help screen as a reminder of options which are understood by the application
Commandline Options:
java -jar xpathtool.jar --help
Commandline Options:
-V Show the current release version for reference
Commandline Options:
java -jar xpathtool.jar -V
1.0-20
Todo:
complete usage message
Definition at line 50 of file XPathSet.java.
References XPathTool.load(), XPathTool.save(), XPathTool.search(), XPathTool.setAttr(), XPathTool.subAttr(), and XPathSet.usage().
static void usage (String proc) inline static
usage messages are useful to those of us with short memories as well (hey, I just need to add swap!)
Parameters
proc name of the process or program (ie wwndesc)
Definition at line 24 of file XPathSet.java.
Referenced by XPathSet.main().
The documentation for this class was generated from the following file:
java/XPathSet.java